project:
  type: website

website:
  title: "Al Norte"
  navbar:
    left: 
      - href: overview.html
        text: Overview
      - href: poster.html
        text: Poster
      - href: proposal.html
        text: Proposal
      - href: methodology.html
        text: Methodology
      - href: analysis.html
        text: Analysis
      - href: findings.html
        text: Results & Discussion

    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

