project:
  type: website

website:
  title: "GIS_Project"
  navbar:
    left: 
      - href: overview.qmd
        text: Overview
      - href: methodology.qmd
        text: Methodology
      - href: Analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Results & Discussion

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

